language: php

sudo: false

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer self-update
  - composer update --prefer-dist --no-interaction

script: ./vendor/bin/phpunit
